// "The verdict": one paragraph per archetype x score band, keyed
// "archetype.band". {strength} and {cost} are filled by kiss-report.js with
// the reader's top strength and top cost titles; pronoun and verb tokens are
// substituted by the client. Some pairs (a Podium Sprinter, a Raw Material
// Natural) are hard or impossible to reach; they exist so nothing renders empty.
export const VERDICTS = {
  "natural.raw": "A Natural at Raw Material is a contradiction, and I don't believe it. Your instincts read, wait, and soften; the score says the execution hasn't caught up with them yet, or you answered on your worst night. Either way, this is unusually good raw material. {strength} is the proof: that is not a beginner's habit. {cost} is where the points went, and it's a habit, not a personality, which means it goes when you tell it to. Read the fixes and take the test again in a week.",
  "natural.better": "Better Than You Think, and you probably think about it less than anyone I've coached, which is the whole Natural trick. Your answers read, wait, and follow. The number lags behind the instinct because a couple of habits are quietly leaking. {strength} is the one to protect; it's the reason nobody has ever had to steer you. {cost} is the leak. Plug it and this score moves fast, because there's nothing to unlearn, only something to stop doing.",
  "natural.dangerous": "Dangerous, in a Good Way, and you got there without a single technique, which is either annoying or the whole point. You run on the other person: you read, you wait, you soften, you move. {strength} is doing most of the work, and it's the kind of thing people remember for years without knowing why. {cost} is the one place even naturals get lazy. Fix that, and the move in this report is the last thing standing between you and the top band.",
  "natural.podium": "Podium. I'd be suspicious if the answers weren't so consistent: you read, you wait, you follow, you move, and you don't think about any of it. {strength} is the headline, and it's the thing most people spend a whole book trying to learn. The closest thing you have to a weak spot is {cost}, and I had to look. So this report isn't about fixing you. It's about the one move you almost certainly haven't found, and it's waiting a few sections down.",
  "slow-burn.raw": "A Slow Burn at Raw Material means you learned the hardest lesson first and skipped the easy ones. You make the wait feel like a decision, which is rarer than a good tongue, and I mean that. But a beautiful pause followed by a kiss that never changes gear is a trailer for a film that doesn't start. {strength} is real. {cost} is the reason the number is low, and it's a mechanical fix, not a personality transplant. Contrast is the whole assignment.",
  "slow-burn.better": "Better Than You Think, and the wait is why. You understand that the moment before the kiss is part of the kiss; most people never get there. What the score is telling you is that after the wait, not enough happens. One speed, held with conviction, is still one speed. {strength} is the thing to keep on principle. {cost} is the thing turning a devastating opener into a predictable middle. This report is about a second gear.",
  "slow-burn.dangerous": "Dangerous, in a Good Way, and you did it slowly, which is the only way it counts. You make people wait and they keep coming back; that's not a technique, it's nerve. The gap between you and the podium is contrast. {strength} is the base. {cost} is the habit that lets {him} predict you by minute two, and a kiss {he} can predict is a kiss {he} can drift through. Slow is your weapon. Now learn to change speed on purpose.",
  "slow-burn.podium": "Podium, and you got there by refusing to hurry, which I respect more than any move in the book. The wait, the eyes, the late tongue: you do the expensive things on instinct. {strength} is the reason {he}'ll think about you at work. {cost} is the closest thing you have to a gap, and it's a small one. So the move in this report isn't a fix. It's the Push, the Stare, the Dive, and it turns a slow kiss into a devastating one.",
  "sweetheart.raw": "A Sweetheart at Raw Material is the most fixable result on the whole board, and I'm not being kind, I'm being accurate. People relax when they kiss you; the score is low because relaxed is where it stays. Safe hands, safe body, safe breath, and nobody's ever dizzy. {strength} is genuinely lovely and you keep it. {cost} is where the points went, and it's the same habit in a different room: waiting to be led. This report is about going first.",
  "sweetheart.better": "Better Than You Think, which for a Sweetheart means everyone enjoys kissing you and nobody's ever been knocked sideways by it. Shoulders drop. That's rare. It's also why the kiss ends as a hug with lips. {strength} is the thing I'd never coach out of you. {cost} is the polite habit that's costing the most, and polite is the word. Once in a while, on purpose, be the one who decides. The score will follow you across the room.",
  "sweetheart.dangerous": "Dangerous, in a Good Way, and you did it while making people feel safe, which most people think is impossible. Your kisses land as kind and confident at the same time. The only thing between you and the podium is that {he} still {v:starts} everything. {strength} is why {his} shoulders drop; {cost} is why {his} balance never quite goes. The move in this report is about being the one who crosses the room, mid-sentence, and starts it.",
  "sweetheart.podium": "Podium, and you got there by being the person people feel safest kissing, which is not the way most people get there. Your hands are kind, your breath is right, your check-ins are attention. {strength} is the reason your kisses are remembered as warm. {cost} is the one habit keeping them from being remembered as dizzying. The gap between warm and dizzying is one decision: who starts it. Tonight, on purpose, that's you.",
  "overthinker.raw": "An Overthinker at Raw Material means three jobs done badly instead of one job done well. You're kissing, narrating, and grading at the same time, and the narration is winning. The good news is buried in the score: instincts leak, they don't vanish. {strength} is proof there's a kisser in there who knows what to do. {cost} is the narrator's favourite habit. Everything in this report is about firing the narrator, not adding to the workload, and that should be a relief.",
  "overthinker.better": "Better Than You Think, and you don't think so, because that's the job the narrator gave you. Your mouth is doing most things right and your head is doing most things else. {strength} is the tell: nobody who's genuinely bad at this has that habit. {cost} is the narrator's handiwork, and it costs more than any technique flaw could, because it costs presence. This report is about removing things, not adding them, and you'll notice that's the easier direction.",
  "overthinker.dangerous": "Dangerous, in a Good Way, which will surprise you and nobody else. The instincts are excellent; the commentary is the only thing in the way. You're one quiet room away from the podium. {strength} is the habit I'd put on a poster. {cost} is the last place the narrator still gets a vote, and it's a small one. The move in this report gives the narrator nothing to say for ten seconds. In my experience, that's usually all it takes.",
  "overthinker.podium": "Podium, with a narrator. That's like winning a race while reading the rulebook out loud, and I'm genuinely impressed. Every instinct is right. {strength} is as good as this gets. {cost} is the one thing left that your head does and your body wouldn't. The report can't improve your technique much, so it does something better: it gives you ten seconds where there's nothing to think about, and shows you what's left when the commentary stops.",
  "explorer.raw": "An Explorer at Raw Material means you know every move on the map and haven't checked whether {he} wanted the tour. Neck, ear, hair, wall, dip, tongue: it's all there, all at once, and none of it is landing, because nothing gets time to. {strength} is the exception, and it's a good one. {cost} is the habit costing the most, and it's the same habit as the other four: doing instead of reading. This report is about doing a third as much.",
  "explorer.better": "Better Than You Think, which for an Explorer means half the tour is genuinely working and the other half is noise. You have range most people never map, and range without a reading is a slideshow. {strength} is the part of the map that's earned. {cost} is the part that's costing you, and it's costing you because it arrived before {he} asked. Do less, watch more, and this score climbs without a single new move.",
  "explorer.dangerous": "Dangerous, in a Good Way, and dangerous is the right word for someone with this many moves. The reading is what's missing: your answers say you do the thing before you've checked whether it was wanted. {strength} is proof that when you follow, it works. {cost} is the last habit still running ahead of {him}. The move in this report is the Mirror: do nothing first, match everything, then add one thing. You have every move. This tells you which one.",
  "explorer.podium": "Podium, and with a full map, which is rare; most people at this level got here by doing less. You did it by having everything and, mostly, using it well. {strength} is the reason the tour works. {cost} is the one stop where you're still performing instead of following. The Mirror in this report isn't a correction. It's the way to find out which of your moves {he} {v:was} hoping for, so you can spend the rest of the night on {him}.",
  "sprinter.raw": "A Sprinter at Raw Material means you arrived with everything, at once, and it landed like a delivery. Speed, pressure, tongue, commitment: nobody doubts you want it, and that's the only thing they're sure of. {strength} is the exception and it's genuinely good. {cost} is the habit costing the most, and the fix for it is the fix for all of them: brakes. Intensity that starts at ten has nowhere to go. This report is about starting at three.",
  "sprinter.better": "Better Than You Think, and you probably think you're excellent, which is the Sprinter's tell. The commitment is real and it's your best quality. The problem is that it's the first thing anyone feels and the last thing they remember, because nothing came before it. {strength} is the habit that's carrying you. {cost} is the one making urgency read as uncertainty. Learn the two-second Pause and the number jumps, because the power was always in the brakes.",
  "sprinter.dangerous": "Dangerous, in a Good Way, which for a Sprinter means you've learned some restraint and kept the engine. That's the hard combination. Nobody wonders whether you want it; now they get a moment to want it back. {strength} is the reason you're here. {cost} is the last habit still starting at ten. The move in this report is the 30% kiss: a third of the pressure, one change every few seconds, and the Reset once. Speed is a tool. Use it last.",
  "sprinter.podium": "Podium, from a Sprinter, means you did the impossible: you kept the commitment and learned to arrive slowly. The wait, the soft first contact, the pressure that invites instead of insists. {strength} is the headline, and it's a converted Sprinter's greatest weapon: restraint with an engine behind it. {cost} is the last trace of the old you, and it's small. The move in this report is about spending ten seconds doing nothing at all, which for you is the final boss.",
  "statue.raw": "A Statue at Raw Material means from the lips out you're trying, and from the collarbone down nobody's home. Hands parked, jaw tight, body still, same move for two minutes. You told me all of this yourself, which is the most useful thing on the page. {strength} is the one part of you that's awake, and it's a real strength. {cost} is the habit costing the most, and it's a hands problem, and hands are the easiest thing in this book to fix. Give them a job.",
  "statue.better": "Better Than You Think, and the reason is that the lips are doing fine; it's everything else that's waiting for a cue. Your kiss is lovely from the neck up and, past that, motionless. {strength} is why people come back. {cost} is why they're not sure you did. This report gives the rest of you a job, starting with your hands, because once your hands move with purpose the body follows without being asked.",
  "statue.dangerous": "Dangerous, in a Good Way, and I'll be honest, I didn't expect a Statue here often. Your mouth is genuinely skilled and your reading is better than your body lets on. {strength} is doing the heavy lifting. {cost} is the one place you're still standing perfectly still, and stillness that isn't chosen reads as absence. The Face Cradle into the Hair Slide in this report is one continuous sentence for your hands. Say it once per kiss and the podium is close.",
  "statue.podium": "Podium, as a Statue, which means everything from the lips up is exceptional and the answers still admit to one thing that never moves. I believe both. {strength} is elite; there's no other word for it. {cost} is the single habit keeping a brilliant kiss from being a whole-body one, and it's a mechanical fix, not a talent gap. The move in this report gives your hands one sentence to say. Everything below the jaw will follow them.",
};
