#!/usr/bin/env python3
"""Unit checks for the Kiss Test article surfaces generated by build_blog.py."""

import re
import unittest

import build_blog


def page_with_final(final_marker: str) -> str:
    """A minimal article page carrying one existing end-of-article block from any marker family."""
    body = "".join(f"<h2>Section {number}</h2><p>{'words ' * 40}</p>" for number in range(1, 9))
    return (
        '<html><body class="bg-charcoal">\n'
        '<a href="/book/?utm_source=howtokissbetter&utm_medium=site&utm_campaign=proof_led_rebuild&utm_content=post_nav"'
        ' data-offer-link data-offer-placement="post-nav" class="bg-gold">\n'
        '    <span class="sm:hidden">Get Book</span>\n'
        '    <span class="hidden sm:inline">Get the book</span>\n'
        "</a>\n"
        f'<div class="article-content">{body}</div>\n'
        f"<!-- {final_marker}_START -->\n<aside>old final</aside>\n<!-- {final_marker}_END -->\n"
        '<script src="/assets/conversion.js?v=20260101" defer></script>\n'
        "</body></html>"
    )


class QuizHookTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.catalog = build_blog.build_offer_catalog()
        cls.posts = {post["slug"]: post for post in build_blog.read_posts()}

    def offer(self, slug: str) -> dict:
        return self.catalog[f"/blog/{slug}/"]

    def buy_offer(self, slug: str, cluster: str) -> dict:
        """A post pinned to the buy rail through its source, the one way a post still gets it."""
        return build_blog.conversion_offer_for_post(self.posts[slug], {"conversion_offer": {"cluster": cluster, "surface": "buy"}})

    def test_load_quiz_data_parses_the_engine_bank(self):
        data = build_blog.load_quiz_data()
        self.assertEqual([question["id"] for question in data["questions"]], [f"q{number}" for number in range(1, 11)])
        for question in data["questions"]:
            self.assertEqual([option["id"] for option in question["options"]], ["a", "b", "c", "d"])
            self.assertTrue(question["prompt"].strip())
        self.assertEqual(build_blog.quiz_question("q10")["id"], "q10")
        with self.assertRaises(KeyError):
            build_blog.quiz_question("q99")

    def test_quiz_hook_renders_one_link_per_option_and_the_label_link(self):
        offer = self.offer("signs-youre-a-good-kisser")
        self.assertEqual(offer["surface"], "quiz")
        markup = build_blog.render_article_quiz_hook(offer)
        question = build_blog.quiz_question(offer["quiz"]["question_id"])
        base = f"/kiss-test/#from=signs-youre-a-good-kisser&amp;hook={offer['offer_key']}&amp;placement=quiz-article-quarter"

        option_links = re.findall(r'<a class="quiz-hook__option" href="([^"]+)" data-offer-link="true"', markup)
        self.assertEqual(
            option_links,
            [f"{base}&amp;q={question['id']}&amp;a={option['id']}" for option in question["options"]],
        )
        self.assertEqual(len(option_links), 4)
        label = build_blog.html.escape(offer["quiz"]["label"])
        self.assertRegex(markup, rf'<a href="{re.escape(base)}" data-offer-link="true"[^>]*>{re.escape(label)}</a> · 10 questions · free result</p>')
        self.assertIn('<p class="quiz-hook__question">', markup)
        self.assertNotRegex(markup, r"\{(?:he|him|his|He|His)\}")
        strip = re.search(
            r'<p class="quiz-hook__which">Which one are you\?</p>\n    <ul class="quiz-hook__archetypes" aria-hidden="true">\n(.*?)\n    </ul>\n    <p class="quiz-hook__question">',
            markup,
            re.DOTALL,
        )
        self.assertIsNotNone(strip)
        self.assertEqual(
            re.findall(r'<li><img src="([^"]+)" alt="" width="240" height="300" loading="lazy" decoding="async"></li>', strip.group(1)),
            [f"/assets/images/kiss-test/archetypes/{archetype}-mw-mini.webp" for archetype in ("natural", "sprinter", "overthinker")],
        )
        self.assertEqual(markup.count("<img"), 3)
        self.assertNotIn("unlock", markup.lower())

    def test_boyfriend_hook_hard_codes_him(self):
        markup = build_blog.render_article_quiz_hook(self.offer("how-to-kiss-your-boyfriend"))
        self.assertIn("&amp;q=q9&amp;a=a", markup)
        self.assertIn("caught him doing?", markup)
        self.assertNotIn("caught them doing?", markup)

    def test_every_post_gets_the_kiss_test_with_a_known_hook(self):
        self.assertEqual(build_blog.BUY_SURFACE_OVERRIDES, set())
        self.assertEqual({offer["surface"] for offer in self.catalog.values()}, {"quiz"})
        # The former buy-rail posts, the crossed-test pins among them, now carry the quiz too.
        for slug in ("how-to-practice-kissing", "signs-youre-a-bad-kisser", "what-to-do-with-your-hands-while-kissing", "how-to-kiss"):
            self.assertEqual(self.offer(slug)["surface"], "quiz", slug)
        for offer in self.catalog.values():
            self.assertIn(offer["offer_key"], build_blog.QUIZ_HOOKS)
            expected = {**build_blog.QUIZ_HOOKS[offer["offer_key"]], **build_blog.QUIZ_HOOK_OVERRIDES.get(offer["article_slug"], {})}
            self.assertEqual(offer["quiz"], expected, offer["article_slug"])
        self.assertEqual(self.offer("how-to-kiss-your-boyfriend")["quiz"]["pronoun"], "him")

    def test_a_pin_still_puts_a_post_on_the_buy_rail(self):
        post = self.posts["what-to-do-with-your-hands-while-kissing"]
        original = set(build_blog.BUY_SURFACE_OVERRIDES)
        build_blog.BUY_SURFACE_OVERRIDES.add(post["slug"])
        try:
            self.assertEqual(build_blog.conversion_offer_for_post(post, {})["surface"], "buy")
        finally:
            build_blog.BUY_SURFACE_OVERRIDES.clear()
            build_blog.BUY_SURFACE_OVERRIDES.update(original)
        self.assertEqual(self.buy_offer(post["slug"], "touch")["surface"], "buy")

    def test_source_override_can_pin_the_surface(self):
        post = {"slug": "test-post", "title": "Test", "description": "", "category": "Techniques", "tags": []}
        source = {"conversion_offer": {"cluster": "technique", "surface": "quiz"}}
        self.assertEqual(build_blog.conversion_offer_for_post(post, source)["surface"], "quiz")
        with self.assertRaises(ValueError):
            build_blog.validate_conversion_override("test-post", {"cluster": "technique", "surface": "nope"})

    def test_strip_removes_every_generated_marker_family(self):
        blocks = "\n".join(
            f"<!-- {marker}_START -->\n<aside>old</aside>\n<!-- {marker}_END -->"
            for marker in (
                "PROOF_LED_QUARTER", "PROOF_LED_MOBILE",
                "BUY_RAIL_QUARTER", "BUY_RAIL_BAR",
                "QUIZ_HOOK_QUARTER", "QUIZ_HOOK_BAR",
            )
        )
        stripped = build_blog.strip_generated_conversion_markup(f"<p>a</p>\n{blocks}\n<p>b</p>")
        for family in ("PROOF_LED_", "BUY_RAIL_", "QUIZ_HOOK_"):
            self.assertNotIn(family, stripped)
        self.assertIn("<p>a</p>", stripped)
        self.assertIn("<p>b</p>", stripped)

    def test_apply_replaces_any_final_family_and_follows_the_arm(self):
        quiz_offer = self.offer("signs-youre-a-good-kisser")
        buy_offer = self.buy_offer("what-to-do-with-your-hands-while-kissing", "touch")
        for marker in ("PROOF_LED_FINAL", "BUY_RAIL_FINAL", "QUIZ_HOOK_FINAL"):
            quiz_page = build_blog.apply_conversion_to_article_page(page_with_final(marker), quiz_offer)
            self.assertNotIn("old final", quiz_page)
            for expected in ("QUIZ_HOOK_QUARTER_START", "QUIZ_HOOK_FINAL_START", "QUIZ_HOOK_BAR_START"):
                self.assertEqual(quiz_page.count(f"<!-- {expected} -->"), 1, expected)
            self.assertNotIn("BUY_RAIL_", quiz_page)
            self.assertNotIn("PROOF_LED_", quiz_page)
            self.assertIn(
                'href="/kiss-test/#from=signs-youre-a-good-kisser&amp;hook=touch&amp;placement=post-nav" data-offer-link',
                quiz_page,
            )
            self.assertIn('<span class="sm:hidden">Kiss Test</span>', quiz_page)
            self.assertIn('<span class="hidden sm:inline">Take the Kiss Test</span>', quiz_page)

            buy_page = build_blog.apply_conversion_to_article_page(quiz_page, buy_offer)
            self.assertNotIn("QUIZ_HOOK_", buy_page)
            for expected in ("BUY_RAIL_QUARTER_START", "BUY_RAIL_FINAL_START", "BUY_RAIL_BAR_START"):
                self.assertEqual(buy_page.count(f"<!-- {expected} -->"), 1, expected)
            self.assertIn("utm_content=post-nav&amp;offer_key=touch#touch", buy_page)
            self.assertIn('<span class="hidden sm:inline">Get the book</span>', buy_page)

    def test_first_build_from_the_template_is_already_stable(self):
        # A rebuild that changed a fresh post's page failed the blog bot's release gate on 2026-09-28.
        body = "".join(f"<h2>Section {number}</h2><p>{'words ' * 40}</p>" for number in range(1, 9))
        template_page = (
            '<html><body class="bg-charcoal">\n'
            f'<div class="article-content">{body}</div>\n'
            "            </div>\n\n"
            "                        <!-- CTA Box -->\n"
            '                        <div class="cta"><p>old cta</p></div>\n\n'
            "                </div><!-- end max-w-3xl -->\n"
            "</body></html>"
        )
        for offer in (self.offer("signs-youre-a-good-kisser"), self.buy_offer("what-to-do-with-your-hands-while-kissing", "touch")):
            first = build_blog.apply_conversion_to_article_page(template_page, offer)
            self.assertNotIn("old cta", first)
            self.assertEqual(build_blog.apply_conversion_to_article_page(first, offer), first, offer["surface"])


if __name__ == "__main__":
    unittest.main()
