#!/usr/bin/env python3
"""Deterministic release checks for the proof-led conversion rebuild."""

from __future__ import annotations

import json
import re
import sys
from collections import Counter
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlparse

ROOT = Path(__file__).resolve().parents[1]
BLOG = ROOT / "blog"
VALID_CLUSTERS = {
    "practice",
    "technique",
    "touch",
    "chemistry",
    "relationship",
    "boundaries",
    "complete-guide",
}
VALID_CHAPTERS = {f"chapter-{number:02d}" for number in range(1, 17)}
VALID_ANCHORS = VALID_CLUSTERS | {"look-inside"}
BOOK_ANCHORS = (VALID_CLUSTERS - {"complete-guide"}) | {"look-inside"}
HOME_ANCHORS = {"moment", "look-inside", "preview", "find-your-path", "pricing", "faq"}
REQUIRED_OFFER_ATTRIBUTES = (
    "data-offer-placement",
    "data-offer-key",
    "data-offer-variant",
    "data-article-slug",
    "data-chapter-id",
)


class LinkCollector(HTMLParser):
    """Collect document IDs and local URL-bearing attributes."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.ids: list[str] = []
        self.urls: list[tuple[str, str]] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        values = dict(attrs)
        element_id = values.get("id")
        if element_id:
            self.ids.append(element_id)
        for attribute in ("href", "src"):
            value = values.get(attribute)
            if value:
                self.urls.append((attribute, value))
        srcset = values.get("srcset")
        if srcset:
            for candidate in srcset.split(","):
                url = candidate.strip().split()[0]
                if url:
                    self.urls.append(("srcset", url))


class Validation:
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.checks = 0

    def require(self, condition: bool, message: str) -> None:
        self.checks += 1
        if not condition:
            self.errors.append(message)

    def equal(self, actual: object, expected: object, message: str) -> None:
        self.require(actual == expected, f"{message}: expected {expected!r}, got {actual!r}")

    def finish(self) -> None:
        if self.errors:
            print(f"FAILED: {len(self.errors)} error(s) across {self.checks} checks", file=sys.stderr)
            for error in self.errors:
                print(f"  - {error}", file=sys.stderr)
            raise SystemExit(1)
        print(f"PASS: {self.checks} proof-led conversion checks")


def load_catalog() -> dict[str, dict[str, object]]:
    source = (ROOT / "assets" / "offer-catalog.js").read_text()
    match = re.fullmatch(
        r"/\* Generated by build_blog\.py\. Do not edit by hand\. \*/\s*"
        r"window\.KPN_OFFER_CATALOG = (\{.*\});\s*",
        source,
        re.DOTALL,
    )
    if not match:
        raise ValueError("assets/offer-catalog.js is not in the generated catalog format")
    return json.loads(match.group(1))


def matching_div_close(html_text: str, opening_start: int) -> int:
    """Return the start offset of the div closing the opening tag at opening_start."""
    opening_end = html_text.find(">", opening_start)
    depth = 1
    for match in re.finditer(r"<div\b[^>]*>|</div>", html_text[opening_end + 1:], re.IGNORECASE):
        if match.group(0).lower().startswith("<div"):
            depth += 1
        else:
            depth -= 1
            if depth == 0:
                return opening_end + 1 + match.start()
    return -1


def page_for_local_url(source_page: Path, raw_url: str) -> tuple[Path | None, str]:
    if raw_url.startswith(("mailto:", "tel:", "javascript:", "data:")):
        return None, ""
    parsed = urlparse(raw_url)
    if parsed.scheme and parsed.scheme not in {"http", "https"}:
        return None, ""
    if parsed.netloc and parsed.netloc not in {"howtokissbetter.com", "www.howtokissbetter.com"}:
        return None, ""
    path = unquote(parsed.path)
    if not path:
        return source_page, parsed.fragment
    if path.startswith("/"):
        target = ROOT / path.lstrip("/")
    else:
        target = source_page.parent / path
    if path.endswith("/") or target.is_dir():
        target /= "index.html"
    return target.resolve(), parsed.fragment


def validate_local_links(validation: Validation, pages: list[Path]) -> None:
    anchor_cache: dict[Path, set[str]] = {}
    for page in pages:
        collector = LinkCollector()
        collector.feed(page.read_text())
        duplicates = [item for item, count in Counter(collector.ids).items() if count > 1]
        validation.require(not duplicates, f"{page.relative_to(ROOT)} has duplicate IDs: {duplicates}")
        anchor_cache[page.resolve()] = set(collector.ids)

        for attribute, raw_url in collector.urls:
            target, fragment = page_for_local_url(page, raw_url)
            if target is None:
                continue
            validation.require(
                target.exists(),
                f"{page.relative_to(ROOT)} has broken {attribute} target: {raw_url}",
            )
            if (
                not target.exists()
                or not fragment
                or target.suffix.lower() not in {".html", ""}
                or target != (ROOT / "book/index.html").resolve()
            ):
                continue
            if target not in anchor_cache:
                target_collector = LinkCollector()
                target_collector.feed(target.read_text())
                anchor_cache[target] = set(target_collector.ids)
            validation.require(
                fragment in anchor_cache[target],
                f"{page.relative_to(ROOT)} links to missing anchor #{fragment} in {target.relative_to(ROOT)}",
            )


def validate_articles(validation: Validation, catalog: dict[str, dict[str, object]]) -> list[Path]:
    posts = json.loads((BLOG / "posts.json").read_text())
    routes = [f"/blog/{post['slug']}/" for post in posts]
    validation.equal(len(posts), 87, "article manifest count")
    validation.equal(len(set(routes)), 87, "unique article route count")
    validation.equal(set(catalog), set(routes), "offer catalog route set")
    for post in posts:
        expected_category_slug = str(post["category"]).lower().replace(" ", "-")
        validation.equal(
            post.get("category_slug"),
            expected_category_slug,
            f"{post['slug']} manifest category slug",
        )

    article_pages: list[Path] = []
    for post in posts:
        slug = post["slug"]
        route = f"/blog/{slug}/"
        offer = catalog[route]
        page = ROOT / route.lstrip("/") / "index.html"
        article_pages.append(page)
        validation.require(page.exists(), f"missing article page for {route}")
        if not page.exists():
            continue
        page_html = page.read_text()
        cluster = str(offer.get("offer_key"))
        chapter = str(offer.get("chapter_id"))
        anchor = str(offer.get("preview_anchor"))

        validation.require(cluster in VALID_CLUSTERS, f"{slug} has invalid cluster {cluster}")
        validation.require(chapter in VALID_CHAPTERS, f"{slug} has invalid chapter {chapter}")
        validation.require(anchor in VALID_ANCHORS, f"{slug} has invalid preview anchor {anchor}")
        validation.equal(offer.get("article_slug"), slug, f"{slug} catalog slug")
        validation.equal(page_html.count("<!-- PROOF_LED_QUARTER_START -->"), 1, f"{slug} quarter offer count")
        validation.equal(page_html.count("<!-- PROOF_LED_FINAL_START -->"), 1, f"{slug} final offer count")
        validation.equal(page_html.count("<!-- PROOF_LED_MOBILE_START -->"), 1, f"{slug} mobile bar count")
        validation.equal(page_html.count('id="article-book-preview"'), 1, f"{slug} quarter offer ID count")
        validation.equal(page_html.count('class="mobile-buy-bar js-offer"'), 1, f"{slug} mobile bar surface count")
        validation.require('$9.99' not in page_html, f"{slug} still contains the stale $9.99 price")
        validation.require(
            f'data-page-kind="article" data-article-slug="{slug}" data-offer-key="{cluster}" data-chapter-id="{chapter}"'
            in page_html,
            f"{slug} body analytics attributes are incomplete",
        )
        validation.require(
            f'<link rel="canonical" href="https://howtokissbetter.com/blog/{slug}/">' in page_html,
            f"{slug} canonical URL changed",
        )
        validation.require(
            '<script src="/assets/offer-catalog.js?v=20260814" defer></script>' in page_html
            and '<script src="/assets/conversion.js?v=20260814" defer></script>' in page_html,
            f"{slug} conversion scripts are incomplete",
        )

        for placement in ("article-quarter", "article-final", "mobile-buy-bar"):
            placement_matches = re.findall(
                rf'<(?:aside|a)\b[^>]*data-offer-placement="{re.escape(placement)}"[^>]*>',
                page_html,
                re.DOTALL,
            )
            validation.equal(len(placement_matches), 2, f"{slug} {placement} surface and link count")
            for tag in placement_matches:
                for attribute in REQUIRED_OFFER_ATTRIBUTES:
                    validation.require(attribute in tag, f"{slug} {placement} tag missing {attribute}")
                validation.require(f'data-offer-key="{cluster}"' in tag, f"{slug} {placement} cluster mismatch")
                validation.require(f'data-chapter-id="{chapter}"' in tag, f"{slug} {placement} chapter mismatch")
                validation.require(f'data-article-slug="{slug}"' in tag, f"{slug} {placement} article mismatch")

            href_match = re.search(
                rf'<a\b[^>]*href="([^"]+)"[^>]*data-offer-placement="{re.escape(placement)}"[^>]*>',
                page_html,
                re.DOTALL,
            )
            validation.require(href_match is not None, f"{slug} {placement} is missing its offer link")
            if href_match:
                expected = (
                    "/book/?utm_source=howtokissbetter&amp;utm_medium=site"
                    f"&amp;utm_campaign=proof_led_rebuild&amp;utm_content={placement}"
                    f"&amp;offer_key={cluster}#{anchor}"
                )
                validation.equal(href_match.group(1), expected, f"{slug} {placement} URL contract")

        content_open = page_html.find('<div class="article-content">')
        quarter_start = page_html.find('<!-- PROOF_LED_QUARTER_START -->', content_open)
        quarter_end = page_html.find('<!-- PROOF_LED_QUARTER_END -->', quarter_start)
        content_close = matching_div_close(page_html, content_open)
        validation.require(
            content_open >= 0 and quarter_start > content_open and quarter_end > quarter_start and content_close > quarter_end,
            f"{slug} article content bounds",
        )
        if content_open >= 0 and quarter_start > content_open and quarter_end > quarter_start:
            before = page_html[content_open:quarter_start]
            after = page_html[quarter_end + len('<!-- PROOF_LED_QUARTER_END -->'):content_close]
            base_length = len(before) + len(after)
            ratio = len(before) / base_length if base_length else 0
            validation.require(0.20 <= ratio <= 0.305, f"{slug} quarter offer ratio is {ratio:.1%}")

    return article_pages


def validate_book(validation: Validation) -> Path:
    page = ROOT / "book" / "index.html"
    page_html = page.read_text()
    collector = LinkCollector()
    collector.feed(page_html)
    anchors = set(collector.ids)

    for anchor in BOOK_ANCHORS:
        validation.require(anchor in anchors, f"book page is missing stable anchor #{anchor}")
    validation.equal(page_html.count('class="book-preview-card"'), 8, "real preview card count")
    validation.equal(page_html.count('data-pathway-panel="'), 6, "book pathway panel count")
    validation.equal(page_html.count('data-pathway="'), 6, "book pathway control count")
    validation.require('data-preview-viewer' in page_html, "book preview dialog is missing")
    validation.require('data-book-sticky' in page_html, "book mobile sticky purchase control is missing")
    validation.require('data-hero-checkout' in page_html, "book hero CTA marker is missing")
    validation.require('<link rel="canonical" href="https://howtokissbetter.com/book/">' in page_html, "book canonical URL changed")
    validation.require('"numberOfPages": 183' in page_html, "book page schema is missing 183 pages")
    validation.require('"price": "4.95"' in page_html, "book page schema has the wrong price")
    validation.require("$9.99" not in page_html, "book page contains the stale $9.99 price")
    validation.require("Hollywood's kissing coach" not in page_html, "book page contains an unsupported authority claim")
    validation.require("star rating" not in page_html.lower(), "book page contains an unsupported rating claim")
    validation.require("countdown" not in page_html.lower(), "book page contains fake urgency")
    validation.require("payhip.com/b/dbMu6" in page_html, "book page is missing the Payhip product")
    validation.require("payhip.com/b/YyLMc" not in page_html, "book page still links to the retired Payhip product")
    validation.require('<link rel="stylesheet" href="/assets/conversion.css?v=20260814a">' in page_html, "book stylesheet is missing")
    validation.require('<script src="/assets/book-preview.js?v=20260814" defer></script>' in page_html, "book preview script is missing")
    validation.require('<script src="/assets/conversion.js?v=20260814" defer></script>' in page_html, "book conversion script is missing")

    hero_media = [
        ROOT / "assets/images/book-proof/cover-320.avif",
        ROOT / "assets/images/book-proof/commandments-title-480.avif",
        ROOT / "assets/images/book-proof/mirror-technique-480.avif",
    ]
    for asset in hero_media:
        validation.require(asset.exists(), f"missing hero proof asset {asset.relative_to(ROOT)}")
    existing = [asset for asset in hero_media if asset.exists()]
    validation.require(sum(asset.stat().st_size for asset in existing) < 500_000, "initial book proof media exceeds 500 KB")
    cover = ROOT / "assets/images/book-proof/cover-320.avif"
    if cover.exists():
        validation.require(cover.stat().st_size < 200_000, "mobile hero cover exceeds 200 KB")
    return page


def validate_home(validation: Validation) -> Path:
    page = ROOT / "index.html"
    page_html = page.read_text()
    collector = LinkCollector()
    collector.feed(page_html)
    anchors = set(collector.ids)

    for anchor in HOME_ANCHORS:
        validation.require(anchor in anchors, f"homepage is missing stable anchor #{anchor}")
    validation.require(
        '<body class="home-shell" data-page-kind="home" data-article-slug="homepage" data-offer-key="chemistry" data-chapter-id="chapter-12">'
        in page_html,
        "homepage analytics body contract is incomplete",
    )
    validation.require(
        "Make the moment happen." in page_html and "Kiss better" in page_html,
        "homepage hero promise changed",
    )
    validation.require("Look inside the $4.95 guide" in page_html, "homepage hero CTA is missing")
    validation.equal(page_html.count('class="home-preview-card"'), 6, "homepage real preview card count")
    validation.equal(page_html.count('data-home-pathway="'), 6, "homepage need-based pathway count")
    validation.equal(page_html.count('class="moment-steps__number"'), 4, "homepage first-kiss step count")
    validation.require(page_html.count("js-offer") >= 4, "homepage tracked offer surface count is incomplete")
    validation.require("data-home-sticky" in page_html, "homepage mobile sticky purchase control is missing")
    validation.require("data-home-hero-cta" in page_html, "homepage hero CTA marker is missing")
    validation.require("homepage_moment_proof" in page_html, "homepage conversion campaign is missing")
    validation.require("conversion_repair" not in page_html, "homepage still uses the stale conversion campaign")
    validation.require("$9.99" not in page_html, "homepage contains the stale $9.99 price")
    validation.require("exit-popup" not in page_html, "homepage still contains the automatic exit popup")
    validation.require("section-fade" not in page_html, "homepage still contains opacity-gated sections")
    validation.require("hero-bg-v2" not in page_html, "homepage still loads the old decorative hero image")
    validation.require("data:image/svg+xml" not in page_html, "homepage still contains the emoji SVG favicon")
    validation.require("Hollywood's kissing coach" not in page_html, "homepage contains an unsupported authority claim")
    validation.require("reader said" not in page_html.lower(), "homepage contains an unsupported reader quote")
    validation.require("data-countdown" not in page_html.lower(), "homepage contains fake urgency")
    validation.require("payhip.com/b/dbMu6" in page_html, "homepage is missing the Payhip product")
    validation.require("payhip.com/b/YyLMc" not in page_html, "homepage still links to the retired Payhip product")
    validation.require('<link rel="canonical" href="https://howtokissbetter.com/">' in page_html, "homepage canonical URL changed")
    validation.require("PDF and EPUB" in page_html, "homepage FAQ schema is missing both delivery formats")
    validation.require('<link rel="stylesheet" href="/assets/conversion.css?v=20260814a">' in page_html, "homepage conversion stylesheet is missing")
    validation.require('<link rel="stylesheet" href="/assets/home.css?v=20260814a">' in page_html, "homepage stylesheet is missing")
    validation.require('<script src="/assets/book-preview.js?v=20260814" defer></script>' in page_html, "homepage preview script is missing")
    validation.require('<script src="/assets/conversion.js?v=20260814" defer></script>' in page_html, "homepage conversion script is missing")

    hero_media = [
        ROOT / "assets/images/book-proof/cover-320.avif",
        ROOT / "assets/images/book-proof/commandments-title-480.avif",
        ROOT / "assets/images/book-proof/mirror-technique-480.avif",
    ]
    for asset in hero_media:
        validation.require(asset.exists(), f"missing homepage hero proof asset {asset.relative_to(ROOT)}")
    existing = [asset for asset in hero_media if asset.exists()]
    validation.require(sum(asset.stat().st_size for asset in existing) < 500_000, "initial homepage proof media exceeds 500 KB")
    cover = ROOT / "assets/images/book-proof/cover-320.avif"
    if cover.exists():
        validation.require(cover.stat().st_size < 200_000, "homepage mobile hero cover exceeds 200 KB")
    return page


def validate_tracking_contract(validation: Validation) -> None:
    source = (ROOT / "assets" / "conversion.js").read_text()
    validation.require('id: "dbMu6"' in source, "tracking script has the wrong Payhip product ID")
    validation.require('id: "YyLMc"' not in source, "tracking script still uses the retired Payhip product ID")
    for event in (
        "offer_view",
        "offer_click",
        "view_item",
        "preview_open",
        "book_pathway_select",
        "home_pathway_select",
        "begin_checkout",
        "generate_lead",
    ):
        validation.require(f'"{event}"' in source, f"tracking script is missing {event}")
    for field in ("page", "article", "placement", "offer_key", "chapter_id", "variant"):
        validation.require(f"{field}:" in source, f"offer event payload is missing {field}")
    validation.require('"kpn_offer_variant_v1"' in source, "persistent offer variant key is missing")
    validation.require('"kpn_generate_lead_v2"' in source, "persistent lead guard key is missing")
    validation.require('window.localStorage' in source, "persistent first-party storage is missing")
    validation.require('window.sessionStorage' in source, "session impression dedupe is missing")
    validation.require('classList.contains("mobile-buy-bar")' in source, "mobile buy bar impression branch is missing")
    validation.require('classList.contains("home-sticky-buy")' in source, "homepage sticky impression branch is missing")
    validation.require('document.body.classList.toggle("has-book-sticky", visible)' in source, "book sticky body state is missing")
    validation.require('document.body.classList.toggle("has-home-sticky", visible)' in source, "homepage sticky body state is missing")
    mobile_function = source[source.index("function setupMobileBuyBar"):source.index("function requestedOfferKey")]
    validation.require("has-book-sticky" not in mobile_function, "article mobile bar leaks the book sticky body state")


def validate_site_safety(validation: Validation) -> None:
    sitemap = (ROOT / "sitemap.xml").read_text()
    validation.require("/book/?" not in sitemap and "offer_key=" not in sitemap, "query-string book variants entered the sitemap")
    validation.equal(sitemap.count("https://howtokissbetter.com/book/"), 1, "canonical book sitemap entry count")

    forbidden = (
        "xkey" + "sib-",
        "/Us" + "ers/",
        "/Us" + "ers/murph/howtokissbetter/" + "_pri" + "vate",
        "_pri" + "vate/keys.txt",
    )
    non_public_dirs = {".git", ".claude", ".codex", ".venv", "_private", "node_modules", "tmp"}
    public_files = [
        path
        for path in ROOT.rglob("*")
        if path.is_file()
        and not non_public_dirs.intersection(path.parts)
        and path.suffix.lower() in {".html", ".js", ".css", ".json", ".py", ".xml", ".txt", ".md"}
    ]
    for path in public_files:
        text = path.read_text(errors="ignore")
        for token in forbidden:
            validation.require(token not in text, f"{path.relative_to(ROOT)} contains forbidden private or credential material")


def validate_override_failures(validation: Validation) -> None:
    sys.path.insert(0, str(ROOT))
    import build_blog  # pylint: disable=import-outside-toplevel

    invalid_cases = (
        {"cluster": "not-a-cluster"},
        {"cluster": "technique", "chapter_id": "chapter-99"},
        {"cluster": "touch", "preview_anchor": "missing"},
        {"cluster": "practice", "extra": "nope"},
    )
    for case in invalid_cases:
        try:
            build_blog.validate_conversion_override("test-post", case)
        except ValueError:
            validation.require(True, "invalid conversion override rejected")
        else:
            validation.require(False, f"invalid conversion override was accepted: {case}")


def main() -> None:
    validation = Validation()
    catalog = load_catalog()
    article_pages = validate_articles(validation, catalog)
    book_page = validate_book(validation)
    home_page = validate_home(validation)
    validate_tracking_contract(validation)
    validate_site_safety(validation)
    validate_override_failures(validation)
    validate_local_links(
        validation,
        article_pages
        + [
            book_page,
            home_page,
            ROOT / "free-chapter-confirmed/index.html",
            ROOT / "blog/index.html",
        ],
    )
    validation.finish()


if __name__ == "__main__":
    main()
